### ISSUE TITLE
[Bug]: Fortran QE model does not work with multiple nuclei in run card

### ISSUE THREAD

**Issue by nastein** [AchillesGen/Achilles#102]
### What happened?

When using the fortran QE model with multiple nuclei in the same run card (say C12 and 1H) a runtime error is encountered 

`At line 28 of file /Users/noah/Desktop/Achilles.nosync/src/Achilles/fortran/currents_opt_v1.f90
Fortran runtime error: Attempting to allocate already allocated variable 'up1'`

This is due to the fact that in `qe_spectral_model.f90` the function `qe_spec_init` calls the subroutine `dirac_matrices_in` from the module `currents_opt_v1.f90` and this subroutine allocates arrays for the nucleon spinors. I believe this is being called twice due to the two different nuclei.

### Run card to reproduce

```yaml
Main:
  NEvents: 100000
  HardCuts: false
  EventCuts: false
  DoRotate: false
  RunDecays: False
  Output:
      Format: NuHepMC
      Name: T2K_H_QE_RES.hepmc
      Zipped: False

SherpaOptions: !include "data/default/SherpaOptions.yml"

Processes:
  - Leptons: [14, [13]]

Beams:
  - Beam:
      PID: 14
      Beam Params:
        Type: Spectrum
        Histogram: flux/T2K_nu.dat
  #       Type: Monochromatic
  #       Energy: 1000
Cascade:
  Run: False
  Interactions:
    - Name: GeantInteraction
      Options:
        GeantData: data/GeantData.hdf5
    - Name: PionInteraction
      Options: 
        HardScatter: 
          Name: MesonBaryonInteraction
          Options:
        Absorption:
          Name: PionAbsorptionOneStep
          Options:
    - Name: ConstantInteraction
      Options:
        InitialStates:
          - Incoming: [3112, 2112]
            Outgoing: 
              - Outgoing: [3112, 2112]
                CrossSection: 0
          - Incoming: [3112, 2212]
            Outgoing: 
              - Outgoing: [3212, 2112]
                CrossSection: 0
          - Incoming: [321, 2212]
            Outgoing: 
              - Outgoing: [321, 2212]
                CrossSection: 0
          - Incoming: [321, 2112]
            Outgoing: 
              - Outgoing: [321, 2112]
                CrossSection: 0
          - Incoming: [3122, 2212]
            Outgoing: 
              - Outgoing: [3122, 2212]
                CrossSection: 0
          - Incoming: [3122, 2112]
            Outgoing: 
              - Outgoing: [3122, 2112]
                CrossSection: 0
          - Incoming: [3212, 2212]
            Outgoing: 
              - Outgoing: [3212, 2212]
                CrossSection: 0
          - Incoming: [3212, 2112]
            Outgoing: 
              - Outgoing: [3212, 2112]
                CrossSection: 0
          - Incoming: [3222, 2112]
            Outgoing: 
              - Outgoing: [3222, 2112]
                CrossSection: 0
          - Incoming: [3222, 2212]
            Outgoing: 
              - Outgoing: [3222, 2212]
                CrossSection: 0
          - Incoming: [311, 2112]
            Outgoing: 
              - Outgoing: [311, 2112]
                CrossSection: 0
          - Incoming: [311, 2212]
            Outgoing: 
              - Outgoing: [311, 2212]
                CrossSection: 0
  Step: 0.04
  Probability: Cylinder
  InMedium: None
  PotentialProp: False
  Algorithm: Base


NuclearModels:
 - NuclearModel:
    Model: FortranModel
    Name: QE_Spectral_Func
    ConfigFile: data/info_C12_pke.data
    FormFactorFile: "FormFactors.yml"
    Ward: None

Nuclei:
  - Nucleus: !include "data/default/12C.yml"
  - Nucleus: !include "data/default/1H.yml"

HardCuts:
  - Type: AngleTheta
    PIDs: 13
    range: [0., 180.]

Options: !include "data/default/OptionDefaults.yml"

Cache:
  Save: False
  Load: False

Backend:
  Name: Default
  Options: []
```

### Log information

```shell

```
